name: Deploy React App to S3 + CloudFront

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0

      - name: Create .env.production fileAdd commentMore actions
        run: |
          echo "VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}" > .env.production
          echo "VITE_TURN_URL=${{ secrets.VITE_TURN_URL }}" >> .env.production
          echo "VITE_TURN_USERNAME=${{ secrets.VITE_TURN_USERNAME }}" >> .env.production
          echo "VITE_TURN_CREDENTIAL=${{ secrets.VITE_TURN_CREDENTIAL }}" >> .env.production

      - name: Show .env.production contents
        run: cat .env.production

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: ✅ Check API endpoint in build output
        run: |
          echo "VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}" > .env.production
          echo "VITE_TURN_URL=${{ secrets.VITE_TURN_URL }}" >> .env.production
          echo "VITE_TURN_USERNAME=${{ secrets.VITE_TURN_USERNAME }}" >> .env.production
          echo "VITE_TURN_CREDENTIAL=${{ secrets.VITE_TURN_CREDENTIAL }}" >> .env.production

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete --acl bucket-owner-full-control
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: dist

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: "/*"
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
